<?php

/**
 * Implements hook_preprocess_page_title().
 */
function logos_preprocess_page_title(&$variables) {

  $logo = \Drupal::request()->attributes->get('logo');

  if ($logo instanceof \Drupal\logos\Entity\Logo) {
    $url_object = \Drupal::service('path.validator')->getUrlIfValid(Drupal::service('path.current')->getPath());
    $route_name = $url_object->getRouteName();
    if ($route_name == 'entity.logo.delete_form') {
      $types = \Drupal\logos\Entity\Logo::getTypes();
      $variables['title'] =  '¿Seguro que quieres eliminar el logo de ' . $types[$logo->get('type')->value] . '?';
    }
  }
}


/**
 * Implements hook_theme().
 */
function logos_theme($existing, $type, $theme, $path) {
  return [
    'block_logo_header' => [
      'template' => 'block-logo-header',
      'variables' => ['url_logo' => NULL],
    ],
    'block_logo_footer' => [
      'template' => 'block-logo-footer',
      'variables' => ['url_logo' => NULL],
    ],
  ];
}
